repos:
  - repo: local
    hooks:
      - id: tsc
        name: Run static type checker
        entry: npx tsc -p tsconfig.app.json --noEmit
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]
      - id: prettier
        name: Run formatter check
        entry: npx prettier --check .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]
      - id: vitest
        name: Run unit tests
        entry: npx ng test --watch=false
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]
